# Zeabur 部署配置文件
# 文档: https://zeabur.com/docs

# 前端服务配置
services:
  # ==================== 后端服务（先部署） ====================
  - name: backend
    type: prebuilt
    path: ./backend
    dockerfile: ./backend/Dockerfile
    env:
      - name: DJANGO_SETTINGS_MODULE
        value: core.settings
      - name: SECRET_KEY
        value: ${SECRET_KEY}
      - name: DJANGO_ALLOWED_HOSTS
        value: ${DJANGO_ALLOWED_HOSTS:-*.zeabur.app}
      - name: DEBUG
        value: "False"
      - name: RABBITMQ_HOST
        value: ${rabbitmq.host}
      - name: RABBITMQ_PORT
        value: ${rabbitmq.port}
      - name: RABBITMQ_USER
        value: ${RABBITMQ_DEFAULT_USER:-guest}
      - name: RABBITMQ_PASSWORD
        value: ${RABBITMQ_DEFAULT_PASS:-guest}
      - name: RABBITMQ_VHOST
        value: /
    ports:
      - port: 8000
        public: true
    # 禁用健康检查，给 Django 足够启动时间
    healthCheckCacheSec: 300

  # ==================== RabbitMQ 消息队列服务 ====================
  - name: rabbitmq
    image: rabbitmq:3.12-management
    env:
      - name: RABBITMQ_DEFAULT_USER
        value: ${RABBITMQ_DEFAULT_USER:-guest}
      - name: RABBITMQ_DEFAULT_PASS
        value: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - port: 5672
        public: false
      - port: 15672
        public: true

  # ==================== 前端服务 ====================
  - name: frontend
    type: prebuilt
    path: ./frontend
    dockerfile: ./frontend/Dockerfile
    env:
      - name: NODE_ENV
        value: production
      - name: BACKEND_URL
        value: ${backend.url}
    ports:
      - port: 80
        public: true

# ==================== 数据卷 ====================
volumes:
  - name: rabbitmq_data
    type: persistent
