# Railway.app Docker Compose 配置
# 自动化测试管理平台 - 完整部署配置

version: "3.8"

services:
  # ==================== RabbitMQ 消息队列 ====================
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,warning}]
    volumes:
      - railway-data:/var/lib/rabbitmq
    # Railway 会自动分配端口并暴露给其他服务
    # 内部访问：rabbitmq:5672
    # 管理界面：rabbitmq:15672

  # ==================== Django 后端 ====================
  backend:
    image: python:3.11-slim
    working_dir: /app
    environment:
      # Django 配置
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-this-in-production}
      DEBUG: ${DEBUG:-False}

      # 数据库配置 (Railway PostgreSQL)
      DATABASE_URL: ${DATABASE_URL}

      # RabbitMQ 配置 (连接到 Railway 上的 RabbitMQ 服务)
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_VHOST: /

      # CORS 配置
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
      CSRF_TRUSTED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
    command: >
      bash -c "
        pip install -q --no-cache-dir -r requirements.txt &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 core.asgi:application
      "

volumes:
  railway-data:
    driver: local
