[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --nomigrations --cov=apps --cov-report=html --cov-report=term
testpaths = apps

[coverage:run]
source = apps
omit =
    */migrations/*
    */tests/*
    */test_*.py
    */__init__.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
