# Generated by Django 4.2.7 on 2026-01-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '管理员'), ('tester', '测试人员'), ('guest', '访客')], default='guest', max_length=20, verbose_name='角色'),
        ),
    ]
