# Generated by Django 4.2.7 on 2026-02-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rabbitmq_enabled',
            field=models.BooleanField(default=False, verbose_name='启用RabbitMQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='rabbitmq_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RabbitMQ密码'),
        ),
    ]
