# Generated by Django 4.2.7 on 2026-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('script_ids', models.JSONField(default=list, verbose_name='包含的脚本列表')),
                ('schedule', models.JSONField(blank=True, default=dict, verbose_name='调度配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'plans_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
