# Generated by Django 4.2.7 on 2026-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='schedule',
        ),
        migrations.AddField(
            model_name='plan',
            name='cron_expression',
            field=models.CharField(blank=True, default='', help_text='例如: 0 2 * * * 表示每天凌晨2点执行', max_length=100, verbose_name='Cron表达式'),
        ),
        migrations.AddField(
            model_name='plan',
            name='schedule_enabled',
            field=models.BooleanField(default=True, verbose_name='启用调度'),
        ),
        migrations.AddField(
            model_name='plan',
            name='schedule_type',
            field=models.CharField(choices=[('manual', '手动执行'), ('cron', '定时执行')], default='manual', max_length=20, verbose_name='执行方式'),
        ),
    ]
