# Generated by Django 4.2.7 on 2026-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_schedule_plan_cron_expression_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_plan_name_per_project', violation_error_message='同一项目下不能存在同名计划'),
        ),
    ]
