# Generated by Django 4.2.7 on 2026-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='数据源名称')),
                ('type', models.CharField(choices=[('json', 'JSON数据'), ('csv', 'CSV文件'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='数据类型')),
                ('data', models.JSONField(default=dict, verbose_name='数据内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'scripts_datasource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('type', models.CharField(choices=[('web', 'Web自动化'), ('mobile', '移动端自动化'), ('api', 'API接口测试')], max_length=20, verbose_name='脚本类型')),
                ('framework', models.CharField(choices=[('selenium', 'Selenium'), ('playwright', 'Playwright'), ('appium', 'Appium'), ('httprunner', 'HttpRunner')], max_length=20, verbose_name='测试框架')),
                ('steps', models.JSONField(default=list, verbose_name='测试步骤')),
                ('is_module', models.BooleanField(default=False, verbose_name='是否为模块')),
                ('module_name', models.CharField(blank=True, max_length=200, verbose_name='模块名称')),
                ('data_driven', models.BooleanField(default=False, verbose_name='是否参数化')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'db_table': 'scripts_script',
                'ordering': ['-created_at'],
            },
        ),
    ]
