# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='variables',
            field=models.JSONField(default=dict, verbose_name='全局变量'),
        ),
        migrations.AddField(
            model_name='script',
            name='timeout',
            field=models.IntegerField(default=30000, verbose_name='超时时间(ms)'),
        ),
        migrations.AddField(
            model_name='script',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='script',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
    ]
