# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_add_script_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, verbose_name='基础URL')),
                ('default_headers', models.JSONField(default=dict, verbose_name='默认请求头')),
                ('auth_type', models.CharField(blank=True, choices=[('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], max_length=20, verbose_name='认证类型')),
                ('auth_config', models.JSONField(default=dict, verbose_name='认证配置')),
                ('sign_enabled', models.BooleanField(default=False, verbose_name='启用签名')),
                ('sign_algorithm', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha256', 'SHA256'), ('hmac-sha256', 'HMAC-SHA256'), ('aes', 'AES'), ('rsa', 'RSA')], max_length=20, verbose_name='签名算法')),
                ('sign_key', models.CharField(blank=True, max_length=500, verbose_name='签名密钥')),
                ('sign_position', models.CharField(blank=True, choices=[('header', '请求头'), ('query', '查询参数'), ('body', '请求体')], max_length=20, verbose_name='签名位置')),
                ('sign_field', models.CharField(blank=True, default='sign', max_length=100, verbose_name='签名字段名')),
                ('mock_enabled', models.BooleanField(default=False, verbose_name='启用Mock')),
                ('mock_response', models.JSONField(default=dict, verbose_name='Mock响应')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to='scripts.script', verbose_name='关联脚本')),
            ],
            options={
                'db_table': 'scripts_apitestconfig',
                'verbose_name': 'API测试配置',
                'verbose_name_plural': 'API测试配置',
            },
        ),
    ]
