# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_add_apitestconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('json', 'JSON数据'), ('csv', 'CSV文件'), ('excel', 'Excel文件'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='数据类型'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_sources/%Y/%m/', verbose_name='数据文件'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='数据行数'),
        ),
    ]
