# Generated by Django 4.2.7 on 2026-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_add_datasource_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_script_name_per_project', violation_error_message='同一项目下不能存在同名脚本'),
        ),
    ]
