# Generated by Django 4.2.7 on 2026-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('selenium', 'Selenium'), ('playwright', 'Playwright'), ('appium', 'Appium')], max_length=20, verbose_name='框架')),
                ('browser', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('edge', 'Edge'), ('safari', 'Safari'), ('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='浏览器/平台')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('download_url', models.URLField(blank=True, verbose_name='下载地址')),
                ('install_command', models.TextField(blank=True, verbose_name='安装命令')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '驱动',
                'verbose_name_plural': '驱动',
                'db_table': 'drivers_driver',
                'ordering': ['framework', 'browser'],
            },
        ),
    ]
