# Generated by Django 4.2.7 on 2026-01-29 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='执行者'),
        ),
        migrations.AddField(
            model_name='execution',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='plans.plan', verbose_name='关联计划'),
        ),
        migrations.AddField(
            model_name='execution',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scripts.script', verbose_name='关联脚本'),
        ),
    ]
