# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'verbose_name': '执行记录', 'verbose_name_plural': '执行记录', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='execution',
            name='breakpoints',
            field=models.JSONField(default=list, verbose_name='断点列表'),
        ),
        migrations.AddField(
            model_name='execution',
            name='current_step_index',
            field=models.IntegerField(default=0, verbose_name='当前步骤索引'),
        ),
        migrations.AddField(
            model_name='execution',
            name='debug_mode',
            field=models.BooleanField(default=False, verbose_name='调试模式'),
        ),
        migrations.AddField(
            model_name='execution',
            name='variables_snapshot',
            field=models.JSONField(default=dict, verbose_name='变量快照'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
