# Generated by Django 4.2.7 on 2026-02-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_add_debug_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='execution_type',
            field=models.CharField(choices=[('plan', '计划执行'), ('script', '脚本执行')], default='script', max_length=20, verbose_name='执行类型'),
        ),
        migrations.AddField(
            model_name='execution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='executions.execution', verbose_name='父执行记录'),
        ),
    ]
