# Generated by Django 4.2.7 on 2026-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_execution_execution_type_execution_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='execution_mode',
            field=models.CharField(choices=[('sequential', '顺序执行'), ('parallel', '并行执行')], default='parallel', max_length=20, verbose_name='执行模式'),
        ),
    ]
