# Generated by Django 4.2.7 on 2026-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_execution_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='显示ID'),
        ),
    ]
