# Generated by Django 4.2.7 on 2026-01-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict, verbose_name='汇总数据')),
                ('html_report', models.FilePathField(blank=True, null=True, path='reports', verbose_name='HTML报告路径')),
                ('charts_data', models.JSONField(default=dict, verbose_name='图表数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='executions.execution', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
