# Generated by Django 4.2.7 on 2026-01-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_add_datasource_file'),
        ('projects', '0002_initial'),
        ('executions', '0003_add_debug_fields'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='步骤索引')),
                ('step_name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('error_type', models.CharField(max_length=100, verbose_name='错误类型')),
                ('error_message', models.TextField(verbose_name='错误消息')),
                ('frequency', models.IntegerField(default=1, verbose_name='出现频次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_analyses', to='executions.execution', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '失败分析',
                'verbose_name_plural': '失败分析',
                'db_table': 'reports_failureanalysis',
                'ordering': ['-frequency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_executions', models.IntegerField(default=0, verbose_name='总执行次数')),
                ('successful_executions', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failed_executions', models.IntegerField(default=0, verbose_name='失败次数')),
                ('pass_rate', models.FloatField(default=0, verbose_name='通过率')),
                ('avg_duration', models.FloatField(default=0, verbose_name='平均耗时(秒)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='projects.project', verbose_name='所属项目')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='scripts.script', verbose_name='关联脚本')),
            ],
            options={
                'verbose_name': '趋势分析',
                'verbose_name_plural': '趋势分析',
                'db_table': 'reports_trendanalysis',
                'ordering': ['-date'],
                'unique_together': {('project', 'script', 'date')},
            },
        ),
    ]
