# Generated by Django 4.2.7 on 2026-02-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_add_debug_fields'),
        ('reports', '0002_failureanalysis_trendanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report',
            field=models.FilePathField(blank=True, null=True, path='reports', verbose_name='PDF报告路径'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='步骤索引')),
                ('step_name', models.CharField(blank=True, max_length=200, verbose_name='步骤名称')),
                ('image_path', models.CharField(max_length=500, verbose_name='图片路径')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, verbose_name='缩略图路径')),
                ('is_error', models.BooleanField(default=False, verbose_name='是否错误截图')),
                ('error_message', models.TextField(blank=True, verbose_name='错误消息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='executions.execution', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '截图',
                'verbose_name_plural': '截图',
                'db_table': 'reports_screenshot',
                'ordering': ['step_index', '-timestamp'],
            },
        ),
    ]
