# Generated by Django 4.2.7 on 2026-02-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_pdf_report_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='html_report',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='HTML报告路径'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_report',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PDF报告路径'),
        ),
    ]
