# Generated by Django 4.2.7 on 2026-01-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0005_add_datasource_file'),
        ('projects', '0002_initial'),
        ('executions', '0003_add_debug_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='执行机ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行机名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌'), ('error', '异常')], default='offline', max_length=20, verbose_name='状态')),
                ('scope', models.CharField(choices=[('global', '全局可用'), ('project', '项目专用')], default='global', max_length=20, verbose_name='作用域')),
                ('max_concurrent', models.IntegerField(default=3, verbose_name='最大并发数')),
                ('current_tasks', models.IntegerField(default=0, verbose_name='当前任务数')),
                ('browser_types', models.JSONField(default=list, verbose_name='支持的浏览器')),
                ('platform', models.CharField(max_length=50, verbose_name='操作系统')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='执行机版本')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bound_projects', models.ManyToManyField(blank=True, related_name='bound_executors', to='projects.project', verbose_name='绑定项目')),
            ],
            options={
                'verbose_name': '执行机',
                'verbose_name_plural': '执行机',
                'db_table': 'executors_executor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='颜色标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '执行机分组',
                'verbose_name_plural': '执行机分组',
                'db_table': 'executors_executorgroup',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#52c41a', max_length=20, verbose_name='颜色标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '执行机标签',
                'verbose_name_plural': '执行机标签',
                'db_table': 'executors_executortag',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('assigned', '已分配'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '正常'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('script_data', models.JSONField(verbose_name='脚本数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='executions.execution', verbose_name='执行记录')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='executors.executor', verbose_name='分配的执行机')),
            ],
            options={
                'verbose_name': '任务队列',
                'verbose_name_plural': '任务队列',
                'db_table': 'executors_taskqueue',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='磁盘使用率')),
                ('current_tasks', models.IntegerField(default=0, verbose_name='当前任务数')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='executors.executor', verbose_name='执行机')),
            ],
            options={
                'verbose_name': '执行机状态日志',
                'verbose_name_plural': '执行机状态日志',
                'db_table': 'executors_executorstatuslog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='executor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='executors', to='executors.executorgroup', verbose_name='分组'),
        ),
        migrations.AddField(
            model_name='executor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='executor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='executors', to='executors.executortag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='变量名')),
                ('value', models.JSONField(verbose_name='变量值')),
                ('type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='变量类型')),
                ('scope', models.CharField(choices=[('project', '项目级'), ('script', '脚本级')], max_length=20, verbose_name='作用域')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='是否敏感')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_variables', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.project', verbose_name='所属项目')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_variables', to='scripts.script', verbose_name='所属脚本')),
            ],
            options={
                'verbose_name': '变量',
                'verbose_name_plural': '变量',
                'db_table': 'executors_variable',
                'ordering': ['scope', 'project', 'script', 'name'],
                'unique_together': {('scope', 'project', 'script', 'name')},
            },
        ),
    ]
