# Generated by Django 4.2.7 on 2026-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('online', '在线'), ('offline', '离线'), ('busy', '忙碌'), ('error', '异常')], default='offline', max_length=20, verbose_name='状态'),
        ),
        migrations.AddConstraint(
            model_name='executor',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_executor_name_per_owner', violation_error_message='同一用户下不能存在同名执行机'),
        ),
    ]
